[dependencies.aura]
default-features = false
package = 'pallet-aura'
version = '2.0.0-alpha.6'

[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.6'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-executive]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.grandpa]
default-features = false
package = 'pallet-grandpa'
version = '2.0.0-alpha.6'

[dependencies.randomness-collective-flip]
default-features = false
package = 'pallet-randomness-collective-flip'
version = '2.0.0-alpha.6'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.sp-api]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-block-builder]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-consensus-aura]
default-features = false
version = '0.8.0-alpha.6'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.6'
features = ["full_crypto"]

[dependencies.sp-application-crypto]
default-features = false
version = '2.0.0-alpha.6'
features = ["full_crypto"]

[dependencies.sp-inherents]
default-features = false
version = '2.0.0-alpha.6'

#[dependencies.sp-io]
#default-features = false
#version = '2.0.0-alpha.6'

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sp-io = { version = "2.0.0-alpha.6", default-features = false, features = [ "disable_oom", "disable_panic_handler" ] }


[dependencies.sp-offchain]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-session]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-transaction-pool]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-version]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sudo]
default-features = false
package = 'pallet-sudo'
version = '2.0.0-alpha.6'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.6'

[dependencies.template]
default-features = false
package = 'pallet-template'
path = '../pallets/template'
version = '2.0.0-alpha.6'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.6'

[dependencies.transaction-payment]
default-features = false
package = 'pallet-transaction-payment'
version = '2.0.0-alpha.6'


[package]
authors = ['Anonymous']
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'sgx-runtime'
repository = 'https://github.com/paritytech/substrate/'
version = '2.0.0-alpha.6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

